"""Build provenance inventories without reading or changing scientific data."""
import csv,hashlib,os,subprocess,sys
from pathlib import Path
ORIGINAL=Path(sys.argv[1]); ROOT=Path(sys.argv[2]); CAPTURE=Path(sys.argv[3]); OUT=ROOT/"refactor_report"
def sha(p):
 h=hashlib.sha256()
 try:
  with p.open("rb") as f:
   for b in iter(lambda:f.read(1024*1024),b""):h.update(b)
  return h.hexdigest()
 except OSError:return ""
def tracked(rel): return subprocess.run(["git","-C",str(ORIGINAL),"ls-files","--error-unmatch",rel],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL).returncode==0
patterns=[]
for base,cat in [("results","historical_result"),("checkpoints","checkpoint"),("manuscript","manuscript_build"),("experiment_log","experiment_log_build")]:
 p=ORIGINAL/base
 if p.exists(): patterns += [(x,cat) for x in p.rglob("*") if x.is_file()]
for p in ORIGINAL.iterdir():
 if p.is_file() and (p.suffix in {".pth",".out"} or p.name=="nohup.out"):patterns.append((p,"root_checkpoint" if p.suffix==".pth" else "root_log"))
with (ROOT/"legacy/artifact_inventory.csv").open("w",newline="") as f:
 w=csv.writer(f);w.writerow(["relative_path","category","size","modification_time","sha256","tracked_status","current_role","proposed_future_destination","physically_moved"])
 for p,c in sorted(patterns):
  rel=str(p.relative_to(ORIGINAL)); st=p.stat(); w.writerow([rel,c,st.st_size,st.st_mtime,sha(p),"tracked" if tracked(rel) else "untracked","historical",f"artifacts/{c}/{p.name}","NO"])
maps=[("src/data_loader/dataset.py","lob_forecasting/data/dataset.py","src/data_loader/dataset.py"),("src/data_loader/preprocess.py","lob_forecasting/data/preprocess.py","src/data_loader/preprocess.py"),("src/data_loader/transforms.py","lob_forecasting/data/transforms.py","src/data_loader/transforms.py"),("src/models/seq2seq.py","lob_forecasting/models/transformers.py","src/models/seq2seq.py")]
with (ROOT/"legacy/path_map.csv").open("w",newline="") as f:
 w=csv.writer(f);w.writerow(["old_path","canonical_path","compatibility_wrapper","migration_status"]);[w.writerow([*r,"moved_and_wrapped"]) for r in maps]
untracked=(CAPTURE/"untracked_files.txt").read_text().splitlines();
with (ROOT/"legacy/untracked_source_inventory.csv").open("w",newline="") as f:
 w=csv.writer(f);w.writerow(["path","copied","destination","source_sha256"])
 for rel in untracked:
  if rel.endswith((".py",".sh")):w.writerow([rel,"YES" if rel.endswith("run_overnight_seed_sweep_20260713.sh") else "NO","experiments/legacy/scripts/run_overnight_seed_sweep_20260713.sh" if rel.endswith("run_overnight_seed_sweep_20260713.sh") else "",sha(ORIGINAL/rel)])
(ROOT/"legacy/removed_autogenerated_files.csv").write_text("removed_path,sha256,comparison_target\n")
